config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'users#my_locations'
	get 'my_locations', to: 'users#my_locations'
	get 'search_locations', to: 'locations#search'
	get 'search_weather', to: 'locations#weather'
	resources :user_locations, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	require 'open-uri'
	has_many :user_locations
	has_many :users, through: :user_locations

	def self.get_json(search_param)
		base_url = 'https://query.yahooapis.com/v1/public/yql'
		query = "select * from weather.forecast where woeid in (select woeid from geo.places(1) where text='#{search_param}')&format=json"
		query_url = "#{base_url}?q=#{query}"

		json = open(query_url).read
		looked_up_location = JSON.parse(json)	
	end

	def self.find_by_city_and_region(city, region)
		base_url = 'https://query.yahooapis.com/v1/public/yql'
		query = "select * from weather.forecast where woeid in (select woeid from geo.places(1) where text='#{city}, #{region}')&format=json"
		query_url = "#{base_url}?q=#{query}"

		json = open(query_url).read
		looked_up_location = JSON.parse(json)	
	end

	def self.get_location(looked_up_location)
		if has_results?(looked_up_location)
			city = get_city(looked_up_location)
			region = get_region(looked_up_location)
			country = get_country(looked_up_location)

			new(city: city, region: region, country: country)
		end
	end

	def self.get_weather(looked_up_location)
		weather = {}
		weather["temp_current"] = get_current_temp(looked_up_location)
		weather["temp_high"] = get_high_temp(looked_up_location)
		weather["temp_low"] = get_low_temp(looked_up_location)
		weather["temp_average"] = get_average_temp(looked_up_location)
		weather
	end

	def self.has_results?(looked_up_location)
		looked_up_location["query"]["count"] > 0
	end

	def self.get_city(looked_up_location)
		 looked_up_location["query"]["results"]["channel"]["location"]["city"]
	end

	def self.get_region(looked_up_location)
		looked_up_location["query"]["results"]["channel"]["location"]["region"]
	end

	def self.get_country(looked_up_location)
		looked_up_location["query"]["results"]["channel"]["location"]["country"]
	end

	def self.get_current_temp(looked_up_location)
		looked_up_location["query"]["results"]["channel"]["item"]["condition"]["temp"]
	end

	def self.get_high_temp(looked_up_location)
		looked_up_location["query"]["results"]["channel"]["item"]["forecast"][0]["high"]
	end

	def self.get_low_temp(looked_up_location)
		looked_up_location["query"]["results"]["channel"]["item"]["forecast"][0]["low"]
	end

	def self.get_average_temp(looked_up_location)
		(looked_up_location["query"]["results"]["channel"]["item"]["forecast"][0]["high"].to_f + 
			looked_up_location["query"]["results"]["channel"]["item"]["forecast"][0]["low"].to_f) / 2
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_locations
	has_many :locations, through: :user_locations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_location?(city, region)
		user_locations.joins(:location).where(locations: { city: city, region: region }).count > 0
	end
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def search
		if params[:search_param].blank?
			flash.now[:danger] = "You have entered an empty search string"
		else
			@location_json = Location.get_json(params[:search_param])
			@location = Location.get_location(@location_json)
			@weather = Location.get_weather(@location_json)
		end

		respond_to do |format|
      format.js { render partial: 'users/result' }
    end
	end

	def weather
			search_string = "#{params[:city]}, #{params[:state]}"
			@location_json = Location.get_json(search_string)
			@location = Location.get_location(@location_json)
			@weather = Location.get_weather(@location_json)

		respond_to do |format|
      format.js { render partial: 'locations/weather' }
    end
	end
end

app/controllers/user_locations_controller.rb
class UserLocationsController < ApplicationController
	def create
		location_json = Location.find_by_city_and_region(params[:city], params[:region])
		looked_up_location = Location.get_location(location_json)
		location = Location.where(city: looked_up_location.city, region: looked_up_location.region)

		if location.blank?
			looked_up_location.save
		end

		@user_location = UserLocation.create(user: current_user, location: looked_up_location)
		flash.now[:success] = "Location #{@user_location.location.city}, #{@user_location.location.region} was successfully added to your list"
		redirect_to my_locations_path
	end

	def destroy
		@user_location = UserLocation.where(user_id: current_user.id, location_id: params[:id]).first
		@user_location.destroy
		flash.now[:notice] = "Location was successfully removed"
		redirect_to my_locations_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def my_locations
		@user = current_user
		@user_locations = current_user.locations
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WeatherApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Weather App", root_path, class:"navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "My Locations", my_locations_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/locations/_list.html.erb
<h1>My Locations</h1>
<table class="table table-striped">
	<thead>
		<tr>
			<th>City</th>
			<th>Region</th>
			<th>Country</th>
			<% if @user.id = current_user.id%>
				<th>Actions</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @user_locations.each do |user_location| %>
			<tr>
				<td><%= user_location.city %></td>
				<td><%= user_location.region %></td>
				<td><%= user_location.country %></td>
				<% if @user.id = current_user.id%>
					<td>
					<%= link_to "Delete", user_location_path(user_location), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
					<%= link_to "View", search_weather_path(:city => user_location.city, :region => user_location.region), params: user_location.city, class: "btn btn-xs btn-success", remote: true %>
					</td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
<table>

app/views/locations/_weather.html.erb
<% if @location && @weather %>
	<h3>Weather for: <%= @location.city %>, <%=@location.region %> <%= @location.country %></h3>
	<div>Current: <%= @weather["temp_current"] %></div>
	<div>High: <%= @weather["temp_high"]%></div>
	<div>Low: <%= @weather["temp_low"] %></div>
	<div>Average: <%= @weather["temp_average"] %></div>
<% end %>

app/views/locations/_weather.js.erb
$('#weather').html("<%= j (render 'locations/weather.html') %>")

app/views/users/_result.html.erb
<div class="results-block">
  <%= bootstrap_flash %>
</div>

<% if @location && @weather%>
	<h1>Search Result</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>City</th>
				<th>Region</th>
				<th>Zip</th>
				<th>Temperature</th>
				<th>High</th>
				<th>Low</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @location.city %></td>
				<td><%= @location.region %></td>
				<td><%= @location.country %></td>
				<td><%= @weather["temp_current"] %></td>
				<td><%= @weather["temp_high"]%></td>
				<td><%= @weather["temp_low"] %></td>
				<% if !current_user.has_location?(@location.city, @location.region) %>
					<td><%= link_to "Add To My Locations", user_locations_path(user: current_user, city: @location.city, 
									region: @location.region), class: "btn btn-xs btn-success", method: :post %> </td>
				<% else %>
					<td><span>Already Added</span></td>
				<% end %>
			</tr>
		</tbody>
	<table>
<% end %>

	

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_locations.html.erb
<h1>Seach Locations</h1>

<%= form_tag search_locations_path, remote: true, method: :get, id: "location-lookup-form" do %>
	<div class="form-group row no-padding text-center col-md-12">
	  <div class="col-md-10">
	  	<%= text_field_tag :search_param, params[:search_param], placeholder: "Search City, State, Zip", autofocus: true, class:"form-control search-box input-lg" %>
	  </div>
	  <div class="col-md-2">
	  	<%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
	  		Search
	  	<% end %>
	  </div>
	</div>
<% end %>

<div id="results">
  <%= render 'result' %>
</div>

<div id="my-locations">
  <%= render 'locations/list' %>
</div>

<div id="weather">
  <%= render 'locations/weather' %>
</div>

app/views/welcome/index.html.erb
<h1>Weather App</h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>